/**
 * Phase 12 — guards the one transcription in the migration.
 *
 * `src/core/db/formsSchema.ts` is a copy of the Realm object graph, generated by
 * scripts/generate-forms-schema.mjs so the SQLite store does not have to import
 * `realm`. A copy can drift, and drift here is not loud: a property missing from
 * the copy would simply stop being ordered — or defaulted — and the wire payload
 * would change shape without anything failing. So this re-derives the schema
 * from src/realmSchema/ (by parsing the sources, not importing them) and
 * compares.
 */
import { buildSchema } from "../scripts/generate-forms-schema.js";
import { FORMS_SCHEMA } from "../src/core/db/formsSchema";

describe("formsSchema.ts", () => {
  const derived = buildSchema();

  it("matches what src/realmSchema declares", () => {
    expect(FORMS_SCHEMA).toEqual(derived);
  });

  it("covers every object type in Realm's config.schema, in order", () => {
    expect((FORMS_SCHEMA as any[]).map(o => o.name)).toEqual(derived.map((o: any) => o.name));
  });

  it("keeps FORMS' property order, which is the order the payload is flattened in", () => {
    const forms = (FORMS_SCHEMA as any[]).find(o => o.name === "FORMS");
    expect(Object.keys(forms.properties)).toEqual([
      "ID", "ACT_NAI", "CHILD", "ISEE", "ACT", "FATHER", "MOTHER",
      "MOTHER_DECEASED", "FATHER_DECEASED", "DEFUNCT", "DECL", "DECES",
      "TYPE", "STATUS", "COLPOINT_CODE", "ERROR",
    ]);
  });

  it("resolves every linked object type", () => {
    const names = new Set((FORMS_SCHEMA as any[]).map(o => o.name));
    const unresolved: string[] = [];
    for (const object of FORMS_SCHEMA as any[]) {
      for (const [property, spec] of Object.entries<any>(object.properties)) {
        const type = typeof spec === "string" ? spec : spec.objectType ?? spec.type;
        if (!["string", "objectId"].includes(type) && !names.has(type)) {
          unresolved.push(`${object.name}.${property} -> ${type}`);
        }
      }
    }
    expect(unresolved).toEqual([]);
  });

  it("keeps the empty-string defaults that made absent fields '' rather than missing", () => {
    const child = (FORMS_SCHEMA as any[]).find(o => o.name === "CHILD");
    expect(child.properties.FIRSTNAME).toEqual({ type: "string", default: "" });
    // FORMS.TYPE/STATUS/COLPOINT_CODE were declared without a default; the form
    // always supplies them.
    const forms = (FORMS_SCHEMA as any[]).find(o => o.name === "FORMS");
    expect(forms.properties.TYPE).toBe("string");
    expect(forms.properties.ERROR).toEqual({ type: "string", default: "" });
  });
});
